FROM pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive  
WORKDIR /app

# Installer OpenCV et outils
RUN apt-get update && apt-get install -y \
    python3-opencv \
    libopencv-dev \
    && rm -rf /var/lib/apt/lists/*


# Copier wheels Linux pour installation offline
COPY wheels_linux/ /wheels/

# Copier requirements
COPY requirements.txt .

# Installer requirements OFFLINE
RUN pip install --no-index --find-links=/wheels -r requirements.txt

# Copier le reste du projet
COPY . .

EXPOSE 8000

CMD ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
